add config.json (in a non-retarded way)
MercuryWorkshop/wisp-server-python pull request #4
Opened 2024-02-14 03:48 UTC by interpolation-0

adds the config.json option outlined by the readme

2024-02-14 03:50 UTC, interpolation-0 commented
i might be fucking stupid

2024-02-14 03:50 UTC, interpolation-0 commented
nvm im good

2024-02-14 03:50 UTC, interpolation-0 commented
or am i

2024-02-14 03:50 UTC, interpolation-0 commented
no im fucking stupid

2024-02-20 21:32 UTC, ading2210 requested changes

2024-02-20 21:32 UTC, ading2210 commented on main.py
> +  def load_config():
Why is this a nested function?

2024-02-20 21:34 UTC, ading2210 requested changes

2024-02-20 21:34 UTC, ading2210 commented on main.py
> +  parser.add_argument("--config", default="config.json", help="The config file location.")
Also, don't make this try to load a nonexistent file as a default. It should only a attempt to load a config file if the `--config` argument is passed in.

2024-09-28 02:45 UTC, ading2210 commented
This PR is stale and has merge conflicts.

2024-09-28 02:45 UTC, closed without merging